Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,6 +17,31 @@ env:
 #   APPUI_TEACHER_PROFILE_IMAGE_NAME: appui-teacher-profile
 #   TAGS: latest
 
+# 🖊️ EDIT your repository secrets to log into your OpenShift cluster and set up the context.
+  # See https://github.com/redhat-actions/oc-login#readme for how to retrieve these values.
+  # To get a permanent token, refer to https://github.com/redhat-actions/oc-login/wiki/Using-a-Service-Account-for-GitHub-Actions
+  OPENSHIFT_SERVER: https://api.atlanta.appui.us:6443
+  OPENSHIFT_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6Ii0xNVhPb3lPa0Ztc3F2ZE1Yem9ET1lWX1Jyanowam1fRXBoUWRKd3A2NnMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtYW51YWwtc2V0dXAtYXBwdWkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZ2l0aHViLWFjdGlvbnMtc2EtdG9rZW4tcXB2OW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ2l0aHViLWFjdGlvbnMtc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIzZWRlZDI0ZS0zNjYwLTQxNTctYTQyNi0xZDZiMDVhYzA2ZDYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bWFudWFsLXNldHVwLWFwcHVpOmdpdGh1Yi1hY3Rpb25zLXNhIn0.WbxxeqVe-5Xz9cRh7Td4358zdQGfHwRVu6RZZ4OHzlGxR378i-6Dy-EaHA5jJZneRmukK7mDzetkdGvphKe19zI0NN-2JyrpUrIUjUHmCiml5GstSUrQMhrKbXVKiKwolAwWEmUGH7Rrh2kU4_cC03zbEqyRkgh6wFui2rL2kPZGbSt4amjPXrsRP2lD9CGypBFzhDttJBpyGWxtvkRnoEtEg_3eMmaG91cG_MtKt_fF4FEPQWL3ODrB_ZrQ9H_3ASZNzO86igkfonH8IeCPdz3UpbSvLQxVkCTUBmAE5vwadN-3l9kcEyTHRZTx7vMpl0LZGU9j4dy3saPU9XC6SvtfaUBPU8TfVEBgYi-Z5q7yfLsSbsB-3dKPGQKkEP5f5RqyEq58ePuy_Hcdj16DkzFA05FoXwVBuUr3thyxkY1XyBLgrP63F4Ar2vDzK4PqBPdtxUYQyMhn913ARk6bqDchKmfjv_fdxV7mzyqmPBcaOeA04_ZfprOvY328-Gli1EogCN9HF8uCiidJkYuHTYS2r2SwcZiMtPgPt02IUUYVwjJsbbJAW95XRh0FyBFdcl_eBjHPSheh7UZ55wXBo5PNpkTSJeuqJcsS1UB2QU0dGVnXXDLnYkuovrteJNFCxc13qOcKfrj51lcN6DN455vZD973AoNXNopCEILiVwI
+  # 🖊️ EDIT to set the kube context's namespace after login. Leave blank to use your user's default namespace.
+  OPENSHIFT_NAMESPACE: quarkus-s2i
+
+  # 🖊️ EDIT to set a name for your OpenShift app, or a default one will be generated below.
+  APP_NAME: appui-comment
+
+  # 🖊️ EDIT with the port your application should be accessible on.
+  # If the container image exposes *exactly one* port, this can be left blank.
+  # Refer to the 'port' input of https://github.com/redhat-actions/oc-new-app
+  APP_PORT: 8080
+
+  # 🖊️ EDIT to change the image registry settings.
+  # Registries such as GHCR, Quay.io, and Docker Hub are supported.
+  IMAGE_REGISTRY: docker.io/aproresco
+  IMAGE_REGISTRY_USER: aproresco
+  IMAGE_REGISTRY_PASSWORD: 7608cf6e-6ca2-4bbb-81aa-a8bc453ea864
+
+  # 🖊️ EDIT to specify custom tags for the container image, or default tags will be generated below.
+  IMAGE_TAGS: latest
+
 # Controls when the workflow will run
 on:
   # Triggers the workflow on push or pull request events but only for the master branch
@@ -34,6 +59,10 @@ jobs:
   build:
     # The type of runner that the job will run on
     runs-on: ubuntu-20.04
+    
+    outputs:
+      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -373,3 +402,120 @@ jobs:
 #           registry: docker.io/aproresco
 #           username: aproresco
 #           password: 7608cf6e-6ca2-4bbb-81aa-a8bc453ea864
+
+
+      - name: Check out repository
+        uses: actions/github-script@v4
+        with:
+          script: |
+            const secrets = {
+              OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER }}`,
+              OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,
+            };
+
+            const GHCR = "ghcr.io";
+            if (`${{ env.IMAGE_REGISTRY }}`.startsWith(GHCR)) {
+              core.info(`Image registry is ${GHCR} - no registry password required`);
+            }
+            else {
+              core.info("A registry password is required");
+              secrets["IMAGE_REGISTRY_PASSWORD"] = `${{ secrets.IMAGE_REGISTRY_PASSWORD }}`;
+            }
+
+            const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
+              if (value.length === 0) {
+                core.error(`Secret "${name}" is not set`);
+                return true;
+              }
+              core.info(`✔️ Secret "${name}" is set`);
+              return false;
+            });
+
+            if (missingSecrets.length > 0) {
+              core.setFailed(`❌ At least one required secret is not set in the repository. \n` +
+                "You can add it using:\n" +
+                "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
+                "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
+                "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
+            }
+            else {
+              core.info(`✅ All the required secrets are set`);
+            }
+
+      - name: Check out repository
+        uses: actions/checkout@v2
+
+      - name: Determine app name
+        if: env.APP_NAME == ''
+        run: |
+          echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
+
+      - name: Determine image tags
+        if: env.IMAGE_TAGS == ''
+        run: |
+          echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
+
+      # https://github.com/redhat-actions/buildah-build#readme
+      - name: Build from Dockerfile
+        id: build-image
+        uses: redhat-actions/buildah-build@v2
+        with:
+          image: ${{ env.APP_NAME }}
+          tags: ${{ env.IMAGE_TAGS }}
+
+          # If you don't have a Dockerfile/Containerfile, refer to https://github.com/redhat-actions/buildah-build#scratch-build-inputs
+          # Or, perform a source-to-image build using https://github.com/redhat-actions/s2i-build
+          # Otherwise, point this to your Dockerfile/Containerfile relative to the repository root.
+          dockerfiles: |
+            ./Dockerfile
+
+      # https://github.com/redhat-actions/push-to-registry#readme
+      - name: Push to registry
+        id: push-image
+        uses: redhat-actions/push-to-registry@v2
+        with:
+          image: ${{ steps.build-image.outputs.image }}
+          tags: ${{ steps.build-image.outputs.tags }}
+          registry: ${{ env.IMAGE_REGISTRY }}
+          username: ${{ env.IMAGE_REGISTRY_USER }}
+          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
+
+      # The path the image was pushed to is now stored in ${{ steps.push-image.outputs.registry-path }}
+
+      - name: Install oc
+        uses: redhat-actions/openshift-tools-installer@v1
+        with:
+          oc: 4
+
+      # https://github.com/redhat-actions/oc-login#readme
+      - name: Log in to OpenShift
+        uses: redhat-actions/oc-login@v1
+        with:
+          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
+          insecure_skip_tls_verify: true
+          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+
+      # This step should create a deployment, service, and route to run your app and expose it to the internet.
+      # https://github.com/redhat-actions/oc-new-app#readme
+      - name: Create and expose app
+        id: deploy-and-expose
+        uses: redhat-actions/oc-new-app@v1
+        with:
+          app_name: ${{ env.APP_NAME }}
+          image: ${{ steps.push-image.outputs.registry-path }}
+          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+          port: ${{ env.APP_PORT }}
+
+      - name: Print application URL
+        env:
+          ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+          SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+        run: |
+          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+          echo
+          echo "======================== Your application is available at: ========================"
+          echo ${{ env.ROUTE }}
+          echo "==================================================================================="
+          echo
+          echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
